#import <Foundation/Foundation.h>
#import <CoreFoundation/CoreFoundation.h>
#include <unistd.h>
#include <signal.h>
#include <spawn.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <arpa/inet.h>

extern char **environ;

// EtcHosts17 system-resolver redirect (the SECONDARY override mechanism).
//
// The PRIMARY mechanism is the scoped managed-DNS profile (com.apple.dnsSettings
// .managed with SupplementalMatchDomains) generated by the Python daemon and
// installed via the Settings bundle. A scoped encrypted-DNS profile is the only
// thing on iOS 17 that outranks an active managed DoH/DoT resolver (ControlD /
// NextDNS / AdGuard) for SPECIFIC hosts, while leaving everything else on the
// primary resolver. The system-resolver redirect here CANNOT beat an active
// managed DoH profile — verified on this device (v0.5.8): writing
// State:/Network/Global/DNS = 127.0.0.1 changed the output key but mDNSResponder
// still queried ControlD over DoH; zero packets reached the daemon.
//
// Where this redirect still wins: plain-DNS networks (Wi-Fi/cellular/Ethernet
// without an active encrypted-DNS profile) and full-tunnel VPN DNS. There it
// points the global resolver at the local daemon, which answers the listed hosts
// and forwards everything else to the captured upstream (the VPN's own DNS).
//
// Reconcile cascade (every 2s + on any SCDynamicStore network change):
//   !Enabled or daemon unhealthy      -> clear our override (system DNS back)
//   VPN active (utun/ipsec/ppp/...)   -> APPLY (local resolver beats VPN DNS;
//                                        the VPN's own DNS is captured into the
//                                        upstreams file so non-listed names are
//                                        forwarded through the tunnel)
//   no VPN + UseDNSProfile ON         -> clear (cede to the scoped profile so
//                                        another DoH profile keeps filtering the
//                                        non-listed names — no conflict)
//   no VPN + UseDNSProfile OFF        -> APPLY (local resolver primary)
//
// Clearing removes only values we wrote and kicks configd so it recomputes the
// real resolver (it will not recompute on its own under a stable VPN).
//
// Usage:
//   etchosts17resolv status        -> print resolver/redirect/VPN state
//   etchosts17resolv apply [ip]    -> force the redirect once
//   etchosts17resolv clear         -> remove the redirect + heal
//   etchosts17resolv watch [ip]    -> reconcile loop (LaunchDaemon mode)

typedef const struct __SCDynamicStore *SCDynamicStoreRef;
typedef void (*SCDynamicStoreCallBack)(SCDynamicStoreRef store, CFArrayRef changedKeys, void *info);
typedef struct {
	CFIndex version;
	void *info;
	const void *(*retain)(const void *info);
	void (*release)(const void *info);
	CFStringRef (*copyDescription)(const void *info);
} SCDynamicStoreContext;

extern SCDynamicStoreRef SCDynamicStoreCreate(CFAllocatorRef allocator, CFStringRef name, SCDynamicStoreCallBack callout, SCDynamicStoreContext *context);
extern CFArrayRef SCDynamicStoreCopyKeyList(SCDynamicStoreRef store, CFStringRef pattern);
extern Boolean SCDynamicStoreSetValue(SCDynamicStoreRef store, CFStringRef key, CFPropertyListRef value);
extern Boolean SCDynamicStoreRemoveValue(SCDynamicStoreRef store, CFStringRef key);
extern CFPropertyListRef SCDynamicStoreCopyValue(SCDynamicStoreRef store, CFStringRef key);
extern Boolean SCDynamicStoreSetNotificationKeys(SCDynamicStoreRef store, CFArrayRef keys, CFArrayRef patterns);
extern CFRunLoopSourceRef SCDynamicStoreCreateRunLoopSource(CFAllocatorRef allocator, SCDynamicStoreRef store, CFIndex order);

static NSString *const kDNSAddrKey = @"ServerAddresses";
static NSString *const kPrefsJB = @"/var/mobile/Library/Preferences/com.ratush.etchosts17.plist";
static NSString *const kUpstreamsJB = @"/var/mobile/Library/EtcHosts17/upstreams";
// Snapshots of each service's ORIGINAL DNS dict, taken before we overwrite it.
// On clear we RESTORE these exactly (never leave a service with no resolver -
// configd does NOT recompute a stable Wi-Fi/cellular/VPN service on its own, so
// a bare RemoveValue kills DNS irreversibly until a PDP/airplane reset).
static NSString *const kOrigDNSDir = @"/var/mobile/Library/EtcHosts17/orig-dns";

static SCDynamicStoreRef gStore = NULL;
static NSString *gRedirectIP = @"127.0.0.1";
static CFAbsoluteTime gLastKick = 0;
static int gProbeFailStreak = 0;
static BOOL gApplied = NO;
static BOOL gDaemonEverAnswered = NO;   // never apply the redirect before the local daemon has answered once
static NSArray<NSString *> *gLastUpstreams = nil;

// configd owns State:/Network/Global/DNS. Kicking it forces a recompute of the
// real resolver from the active service (VPN/Wi-Fi) - the only way to restore
// DNS after our override is removed, because configd does not recompute on its
// own under a stable VPN. Debounced so a persistently-empty resolver (no
// network) does not thrash configd.
static void kickConfigd(BOOL force) {
	CFAbsoluteTime now = CFAbsoluteTimeGetCurrent();
	if (!force && gLastKick != 0 && (now - gLastKick) < 20.0) return;
	gLastKick = now;
	const char *launchctl = "/var/jb/usr/bin/launchctl";
	char *const argv[] = {(char *)launchctl, (char *)"kickstart", (char *)"-k",
						  (char *)"user/501/com.apple.configd", NULL};
	pid_t pid = 0;
	if (posix_spawn(&pid, launchctl, NULL, NULL, argv, environ) == 0) {
		int status = 0;
		waitpid(pid, &status, 0);
	}
}

static BOOL isLoopback(NSString *ip) {
	return [ip hasPrefix:@"127."] || [ip isEqualToString:@"::1"] || [ip isEqualToString:@"0.0.0.0"];
}

static NSArray<NSString *> *serviceDNSKeys(SCDynamicStoreRef store) {
	CFArrayRef keys = SCDynamicStoreCopyKeyList(store, CFSTR("State:/Network/Service/[^/]+/DNS"));
	NSArray *out = (__bridge_transfer NSArray *)keys;
	return out ?: @[];
}

static NSArray<NSString *> *dnsServersAtKey(SCDynamicStoreRef store, CFStringRef key) {
	NSDictionary *value = (__bridge_transfer NSDictionary *)SCDynamicStoreCopyValue(store, key);
	NSArray *addrs = value[kDNSAddrKey];
	return [addrs isKindOfClass:NSArray.class] ? addrs : @[];
}

static BOOL serversAreOurs(NSArray<NSString *> *addrs) {
	if (addrs.count == 0) return NO;
	// "Ours" = every listed server is loopback/our redirect IP. Being liberal
	// here means we never mistake our own override for a real resolver to snapshot.
	for (NSString *ip in addrs) {
		if (![ip isKindOfClass:NSString.class]) return NO;
		if (![ip isEqualToString:gRedirectIP] && !isLoopback(ip)) return NO;
	}
	return YES;
}

// ---------------------------------------------------------------------------
// Original-DNS snapshots: restore-on-clear so inactivity ALWAYS returns stock DNS
// ---------------------------------------------------------------------------

// Map an SC key like State:/Network/Service/ABC-123/DNS to a safe filename.
static NSString *snapshotPathForKey(NSString *key) {
	NSMutableString *safe = [NSMutableString string];
	for (NSUInteger i = 0; i < key.length; i++) {
		unichar c = [key characterAtIndex:i];
		[safe appendFormat:@"%@", (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
			(c >= '0' && c <= '9') || c == '-' ? [NSString stringWithCharacters:&c length:1] : @"_"];
	}
	return [kOrigDNSDir stringByAppendingPathComponent:safe];
}

// Save the current (real) DNS dict at a key before overwriting it, but ONLY if
// it is a genuine resolver (not our own override and not already snapshotted).
static void snapshotOriginal(SCDynamicStoreRef store, NSString *key) {
	NSString *path = snapshotPathForKey(key);
	if ([NSFileManager.defaultManager fileExistsAtPath:path]) return;   // keep the first real value
	NSDictionary *value = (__bridge_transfer NSDictionary *)SCDynamicStoreCopyValue(store, (__bridge CFStringRef)key);
	NSArray *addrs = [value isKindOfClass:NSDictionary.class] ? value[kDNSAddrKey] : nil;
	if (![addrs isKindOfClass:NSArray.class] || addrs.count == 0) {
		fprintf(stderr, "snapshot skip %s: no real addrs\n", key.UTF8String);
		return;   // nothing real to save
	}
	if (serversAreOurs(addrs)) { fprintf(stderr, "snapshot skip %s: ours\n", key.UTF8String); return; }
	NSError *derr = nil;
	[NSFileManager.defaultManager createDirectoryAtPath:kOrigDNSDir withIntermediateDirectories:YES attributes:nil error:&derr];
	// The SC value dict may carry non-plist meta keys; snapshot just the
	// ServerAddresses so writeToFile always succeeds and restore is exact.
	NSDictionary *slim = @{kDNSAddrKey: addrs};
	BOOL wrote = [slim writeToFile:path atomically:YES];
	chmod(path.fileSystemRepresentation, 0644);
	fprintf(stderr, "snapshot %s: %s (%lu addrs) dir=%s\n", key.UTF8String,
			wrote ? "saved" : "WRITE FAILED", (unsigned long)addrs.count,
			derr ? derr.localizedDescription.UTF8String : "ok");
}

// Restore the snapshotted original DNS dict at a key. Returns YES if a snapshot
// existed and was written back. Deletes the snapshot afterwards.
static BOOL restoreOriginal(SCDynamicStoreRef store, NSString *key) {
	NSString *path = snapshotPathForKey(key);
	NSDictionary *value = [NSDictionary dictionaryWithContentsOfFile:path];
	if (![value isKindOfClass:NSDictionary.class]) return NO;
	SCDynamicStoreSetValue(store, (__bridge CFStringRef)key, (__bridge CFPropertyListRef)value);
	[NSFileManager.defaultManager removeItemAtPath:path error:nil];
	return YES;
}

// Force mDNSResponder to drop stale resolver state after a restore.
static void restartMDNS(void) {
	const char *killall = "/var/jb/usr/bin/killall";
	char *const argv[] = {(char *)killall, (char *)"-HUP", (char *)"mDNSResponder", NULL};
	pid_t pid = 0;
	if (posix_spawn(&pid, killall, NULL, NULL, argv, environ) == 0) {
		int status = 0;
		waitpid(pid, &status, 0);
	}
}

// ---------------------------------------------------------------------------
// Preferences (Settings bundle writes both plist copies; read the newest)
// ---------------------------------------------------------------------------

static NSDictionary *readPrefs(void) {
	NSDictionary *prefs = [NSDictionary dictionaryWithContentsOfFile:kPrefsJB];
	return [prefs isKindOfClass:NSDictionary.class] ? prefs : @{};
}

static BOOL boolPref(NSDictionary *prefs, NSString *key, BOOL fallback) {
	id value = prefs[key];
	return [value respondsToSelector:@selector(boolValue)] ? [value boolValue] : fallback;
}

// ---------------------------------------------------------------------------
// Daemon health probe: h.resolver.arpa answered instantly by the daemon's DDR
// suppression path (an upstream-forwarded name can take >0.4s and would cause
// false "unhealthy" clears - measured in v0.5.6).
// ---------------------------------------------------------------------------

static BOOL daemonAnswersOnce(void) {
	static uint16_t txid = 0x1717;
	txid++;
	// header + QNAME h.resolver.arpa + QTYPE A + QCLASS IN
	uint8_t query[64];
	size_t off = 0;
	query[off++] = txid >> 8; query[off++] = txid & 0xFF;
	query[off++] = 0x01; query[off++] = 0x00;   // RD
	query[off++] = 0x00; query[off++] = 0x01;   // QDCOUNT 1
	memset(query + off, 0, 6); off += 6;
	const char *labels[] = {"h", "resolver", "arpa", NULL};
	for (int i = 0; labels[i]; i++) {
		size_t len = strlen(labels[i]);
		query[off++] = (uint8_t)len;
		memcpy(query + off, labels[i], len);
		off += len;
	}
	query[off++] = 0x00;
	query[off++] = 0x00; query[off++] = 0x01;   // A
	query[off++] = 0x00; query[off++] = 0x01;   // IN

	int sock = socket(AF_INET, SOCK_DGRAM, 0);
	if (sock < 0) return NO;
	struct timeval tv = {0, 900000};
	setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
	struct sockaddr_in addr;
	memset(&addr, 0, sizeof(addr));
	addr.sin_family = AF_INET;
	addr.sin_port = htons(53);
	addr.sin_addr.s_addr = inet_addr("127.0.0.1");

	BOOL ok = NO;
	if (sendto(sock, query, off, 0, (struct sockaddr *)&addr, sizeof(addr)) == (ssize_t)off) {
		uint8_t reply[512];
		ssize_t got = recv(sock, reply, sizeof(reply), 0);
		ok = (got >= 2 && reply[0] == (txid >> 8) && reply[1] == (txid & 0xFF));
	}
	close(sock);
	if (ok) gDaemonEverAnswered = YES;
	return ok;
}

// 3-strike hysteresis: one lost UDP packet must not tear the redirect down.
static BOOL daemonHealthy(void) {
	if (daemonAnswersOnce()) {
		gProbeFailStreak = 0;
		return YES;
	}
	gProbeFailStreak++;
	return gProbeFailStreak < 3;
}

// ---------------------------------------------------------------------------
// VPN detection: a tunnel PrimaryInterface means a full-tunnel VPN owns the
// default route (and would otherwise own DNS).
// ---------------------------------------------------------------------------

static BOOL vpnActive(SCDynamicStoreRef store) {
	NSDictionary *g = (__bridge_transfer NSDictionary *)SCDynamicStoreCopyValue(store, CFSTR("State:/Network/Global/IPv4"));
	NSString *iface = g[@"PrimaryInterface"];
	if (![iface isKindOfClass:NSString.class]) return NO;
	for (NSString *prefix in @[@"utun", @"ipsec", @"ppp", @"tun", @"tap"]) {
		if ([iface hasPrefix:prefix]) return YES;
	}
	return NO;
}

// ---------------------------------------------------------------------------
// Upstream capture: before overwriting a DNS key, remember the real servers
// (the VPN's own DNS included) so the daemon forwards non-listed names to them
// instead of hardcoded public IPs a tunnel may block.
// ---------------------------------------------------------------------------

static void captureUpstreams(SCDynamicStoreRef store) {
	NSMutableArray<NSString *> *servers = [NSMutableArray array];
	NSMutableSet<NSString *> *seen = [NSMutableSet set];
	void (^collect)(NSArray<NSString *> *) = ^(NSArray<NSString *> *addrs) {
		for (NSString *ip in addrs) {
			if (![ip isKindOfClass:NSString.class]) continue;
			if (isLoopback(ip) || [ip isEqualToString:gRedirectIP]) continue;
			if ([seen containsObject:ip]) continue;
			[seen addObject:ip];
			[servers addObject:ip];
		}
	};
	collect(dnsServersAtKey(store, CFSTR("State:/Network/Global/DNS")));
	for (NSString *key in serviceDNSKeys(store)) {
		collect(dnsServersAtKey(store, (__bridge CFStringRef)key));
	}
	if (!servers.count || [servers isEqualToArray:gLastUpstreams]) return;
	gLastUpstreams = [servers copy];
	NSString *text = [[servers componentsJoinedByString:@"\n"] stringByAppendingString:@"\n"];
	for (NSString *path in @[kUpstreamsJB]) {
		[NSFileManager.defaultManager createDirectoryAtPath:path.stringByDeletingLastPathComponent
								withIntermediateDirectories:YES attributes:nil error:nil];
		[text writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:nil];
		chmod(path.fileSystemRepresentation, 0644);
	}
	fprintf(stderr, "captured upstreams: %s\n", [servers componentsJoinedByString:@", "].UTF8String);
}

// ---------------------------------------------------------------------------
// Apply / clear
// ---------------------------------------------------------------------------

// We override ONLY the global resolver key. The per-service State DNS keys are
// left untouched, because they are populated from the DHCP/PDP lease and configd
// does NOT recompute them on demand - overwriting/removing them is what left the
// cellular service with a dead resolver in earlier builds. With per-service DNS
// intact, clearing the global override lets configd recompute the real global
// resolver reliably (observed: global returns to the Wi-Fi/cellular DNS).
static NSString *const kGlobalDNSKey = @"State:/Network/Global/DNS";

static void applyRedirect(SCDynamicStoreRef store) {
	captureUpstreams(store);
	if (!serversAreOurs(dnsServersAtKey(store, (__bridge CFStringRef)kGlobalDNSKey))) {
		snapshotOriginal(store, kGlobalDNSKey);
		NSDictionary *ours = @{kDNSAddrKey: @[gRedirectIP]};
		SCDynamicStoreSetValue(store, (__bridge CFStringRef)kGlobalDNSKey, (__bridge CFPropertyListRef)ours);
	}
	if (!gApplied) {
		gApplied = YES;
		fprintf(stderr, "redirect applied -> %s (global only)\n", gRedirectIP.UTF8String);
	}
}

// Restore stock DNS. Global: write back the snapshot if we have one, else remove
// our value so configd recomputes from the untouched per-service DNS. Then also
// HEAL any per-service key an OLDER build left pointing at us (restore snapshot,
// else remove). Always kick configd + reload mDNSResponder. This guarantees that
// any inactivity of the tweak returns fully working stock DNS.
static void clearRedirect(SCDynamicStoreRef store) {
	BOOL touched = NO;

	if (serversAreOurs(dnsServersAtKey(store, (__bridge CFStringRef)kGlobalDNSKey))) {
		if (!restoreOriginal(store, kGlobalDNSKey)) {
			SCDynamicStoreRemoveValue(store, (__bridge CFStringRef)kGlobalDNSKey);
		}
		touched = YES;
	}
	// Legacy heal: builds <=0.5.16 also overrode per-service DNS. If any is still
	// ours, restore it (snapshot) or remove it so no service is stuck at 127.0.0.1.
	for (NSString *key in serviceDNSKeys(store)) {
		if (serversAreOurs(dnsServersAtKey(store, (__bridge CFStringRef)key))) {
			if (!restoreOriginal(store, key)) {
				SCDynamicStoreRemoveValue(store, (__bridge CFStringRef)key);
			}
			touched = YES;
		}
	}

	if (touched) {
		kickConfigd(YES);
		restartMDNS();
	}
	if (gApplied) {
		gApplied = NO;
		fprintf(stderr, "redirect cleared (stock DNS restored)\n");
	}
	// Heal: if the global resolver somehow ended up empty, nudge configd again.
	NSArray *addrs = dnsServersAtKey(store, (__bridge CFStringRef)kGlobalDNSKey);
	if (!addrs.count) kickConfigd(NO);
}

// Force-clear everything ours regardless of tracked state (CLI/uninstall path).
static void clearAll(SCDynamicStoreRef store) {
	gApplied = YES;   // force the log + kick path
	clearRedirect(store);
}

// ---------------------------------------------------------------------------
// Reconcile cascade
// ---------------------------------------------------------------------------

static void reconcile(void) {
	if (!gStore) return;
	NSDictionary *prefs = readPrefs();
	BOOL enabled = boolPref(prefs, @"Enabled", YES);
	BOOL useProfile = boolPref(prefs, @"UseDNSProfile", NO);

	if (!enabled || !daemonHealthy()) {
		clearRedirect(gStore);
		return;
	}
	// Boot safety: never overwrite the stock resolver until the local daemon has
	// actually answered at least once. Otherwise, if the python daemon is slow to
	// start or gets jetsam-killed under LTE, we would point DNS at a dead
	// 127.0.0.1 and break resolution. Until then, keep stock DNS intact.
	if (!gApplied && !gDaemonEverAnswered) {
		clearRedirect(gStore);   // no-op if nothing of ours is set
		return;
	}
	// Under a VPN the local resolver must win no matter what (the scoped
	// profile cannot beat a full-tunnel VPN); without a VPN, profile mode
	// cedes DNS so the user's other DoH profile keeps serving non-listed names.
	if (useProfile && !vpnActive(gStore)) {
		clearRedirect(gStore);
		return;
	}
	applyRedirect(gStore);
}

static void printStatus(SCDynamicStoreRef store) {
	NSArray *addrs = dnsServersAtKey(store, CFSTR("State:/Network/Global/DNS"));
	NSDictionary *prefs = readPrefs();
	fprintf(stdout, "global DNS: %s\n", addrs.count ? addrs.description.UTF8String : "(none)");
	fprintf(stdout, "redirected: %s\n", serversAreOurs(addrs) ? "yes" : "no");
	fprintf(stdout, "vpn: %s\n", vpnActive(store) ? "yes" : "no");
	fprintf(stdout, "enabled pref: %s  use-profile pref: %s\n",
			boolPref(prefs, @"Enabled", YES) ? "yes" : "no",
			boolPref(prefs, @"UseDNSProfile", NO) ? "yes" : "no");
	fprintf(stdout, "daemon: %s\n", daemonAnswersOnce() ? "healthy" : "no answer");
	int redirected = 0, total = 0;
	for (NSString *key in serviceDNSKeys(store)) {
		total++;
		if (serversAreOurs(dnsServersAtKey(store, (__bridge CFStringRef)key))) redirected++;
	}
	fprintf(stdout, "service DNS keys: %d/%d redirected\n", redirected, total);
}

static void changed(SCDynamicStoreRef store, CFArrayRef changedKeys, void *info) {
	(void)store; (void)changedKeys; (void)info;
	reconcile();
}

static void timerTick(CFRunLoopTimerRef timer, void *info) {
	(void)timer; (void)info;
	reconcile();
}

static void onTerm(int sig) {
	(void)sig;
	if (gStore) clearAll(gStore);   // restore system DNS on stop/upgrade
	_exit(0);
}

int main(int argc, char **argv) {
	@autoreleasepool {
		NSString *mode = argc > 1 ? @(argv[1]) : @"status";
		if (argc > 2 && argv[2] && argv[2][0]) gRedirectIP = @(argv[2]);
		SCDynamicStoreContext ctx = {0, NULL, NULL, NULL, NULL};
		gStore = SCDynamicStoreCreate(NULL, CFSTR("com.ratush.etchosts17.resolv"), changed, &ctx);
		if (!gStore) { fprintf(stderr, "no dynamic store\n"); return 1; }

		if ([mode isEqualToString:@"status"]) { printStatus(gStore); return 0; }
		if ([mode isEqualToString:@"clear"])  { clearAll(gStore); return 0; }
		if ([mode isEqualToString:@"apply"])  { applyRedirect(gStore); return 0; }

		if ([mode isEqualToString:@"watch"]) {
			signal(SIGTERM, onTerm);
			signal(SIGINT, onTerm);
			// Startup hygiene: State: keys are ephemeral, so after a reboot our
			// override is already gone. First restore/heal anything a hard-killed
			// prior instance left behind, then purge stale snapshots so we never
			// restore a DNS value captured on a different network.
			clearRedirect(gStore);
			[NSFileManager.defaultManager removeItemAtPath:kOrigDNSDir error:nil];
			gApplied = NO;
			// React to resolver rewrites by configd, VPN connect/disconnect
			// (Global/IPv4 + new per-service DNS keys) - plus a 2s timer for
			// preference flips and daemon-health transitions.
			NSArray *keys = @[@"State:/Network/Global/DNS", @"State:/Network/Global/IPv4"];
			NSArray *patterns = @[@"State:/Network/Service/[^/]+/DNS"];
			SCDynamicStoreSetNotificationKeys(gStore, (__bridge CFArrayRef)keys, (__bridge CFArrayRef)patterns);
			CFRunLoopSourceRef src = SCDynamicStoreCreateRunLoopSource(NULL, gStore, 0);
			CFRunLoopAddSource(CFRunLoopGetCurrent(), src, kCFRunLoopCommonModes);
			CFRunLoopTimerRef timer = CFRunLoopTimerCreate(NULL, CFAbsoluteTimeGetCurrent() + 2.0, 2.0, 0, 0, timerTick, NULL);
			CFRunLoopAddTimer(CFRunLoopGetCurrent(), timer, kCFRunLoopCommonModes);
			reconcile();
			CFRunLoopRun();
			return 0;
		}
		fprintf(stderr, "usage: etchosts17resolv status|apply|clear|watch [redirect-ip]\n");
		return 2;
	}
}
