#import "Shared.h"
#import <Preferences/PSListController.h>
#import <Preferences/PSViewController.h>
#import <Preferences/PSSpecifier.h>
#import <UIKit/UIKit.h>
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
static NSString *RAMText(NSNumber *bytes,BOOL known){return known?[NSString stringWithFormat:@"≈%.1f МБ",bytes.doubleValue/1000000.0]:@"нет данных";}
@interface RPCatalogCell : UITableViewCell
@property(nonatomic,strong) UIButton *infoButton;
@property(nonatomic,strong) UILabel *nameLabel;
@end
@implementation RPCatalogCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString*)rid {
 if((self=[super initWithStyle:style reuseIdentifier:rid])){
  _infoButton=[UIButton buttonWithType:UIButtonTypeSystem];[_infoButton setImage:[UIImage systemImageNamed:@"info.circle"] forState:UIControlStateNormal];_infoButton.tintColor=UIColor.systemBlueColor;_infoButton.translatesAutoresizingMaskIntoConstraints=NO;
  _nameLabel=[[UILabel alloc] init];_nameLabel.font=[UIFont systemFontOfSize:13 weight:UIFontWeightMedium];_nameLabel.numberOfLines=2;_nameLabel.translatesAutoresizingMaskIntoConstraints=NO;
  [self.contentView addSubview:_infoButton];[self.contentView addSubview:_nameLabel];
  [NSLayoutConstraint activateConstraints:@[[_infoButton.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:8],[_infoButton.widthAnchor constraintEqualToConstant:36],[_infoButton.topAnchor constraintEqualToAnchor:self.contentView.topAnchor],[_infoButton.bottomAnchor constraintEqualToAnchor:self.contentView.bottomAnchor],[_nameLabel.leadingAnchor constraintEqualToAnchor:_infoButton.trailingAnchor constant:4],[_nameLabel.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:-8],[_nameLabel.centerYAnchor constraintEqualToAnchor:self.contentView.centerYAnchor]]];
  UISwitch *sw=[[UISwitch alloc] init];sw.on=NO;sw.enabled=NO;self.accessoryView=sw;self.selectionStyle=UITableViewCellSelectionStyleNone;
 }return self;
}
@end
@interface RPProtectedController : PSViewController <UISearchBarDelegate,UITableViewDelegate,UITableViewDataSource>
@property int memoryToken;
@property(nonatomic,strong) UITableView *tableView;
@property(nonatomic,strong) NSArray *inventory;
@property(nonatomic,strong) NSArray *filtered;
@end
@interface RPListController : PSListController <UIDocumentPickerDelegate>
@property int notificationToken;
@property(nonatomic,copy) NSString *pendingRequest;
- (NSString*)pageKind;
@end
@interface RPPresetsController : RPListController @end
@interface RPDaemonsController : RPListController @end
@interface RPCCController : RPListController @end
@interface RPReviewedController : RPListController @end
@implementation RPListController
- (NSString*)pageKind {return @"menu";}
- (instancetype)init {if((self=[super init])){__weak RPListController *w=self;notify_register_dispatch("com.ratush.daemonpresets.changed",&_notificationToken,dispatch_get_main_queue(),^(int t){[w reloadSpecifiers];w.view.userInteractionEnabled=YES;[w libraryReply];});}return self;}
- (void)dealloc {notify_cancel(_notificationToken);}
- (void)viewWillAppear:(BOOL)a {[super viewWillAppear:a];self.title=@{@"menu":@"Демоны iOS",@"presets":@"Пресеты",@"jobs":@"Демоны",@"cc":@"Пресеты в пункте управления",@"reviewed":@"Отключаемые демоны"}[[self pageKind]];Command(@"query");[self reloadSpecifiers];}
- (void)send:(NSString*)c {self.view.userInteractionEnabled=NO;Command(c);dispatch_after(dispatch_time(DISPATCH_TIME_NOW,8*NSEC_PER_SEC),dispatch_get_main_queue(),^{self.view.userInteractionEnabled=YES;});}
- (PSSpecifier*)group:(NSString*)name footer:(NSString*)footer {PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:NULL get:NULL detail:Nil cell:PSGroupCell edit:Nil];[s setProperty:footer forKey:@"footerText"];return s;}
- (PSSpecifier*)link:(NSString*)name detail:(Class)detail {return [PSSpecifier preferenceSpecifierNamed:name target:self set:NULL get:NULL detail:detail cell:PSLinkCell edit:Nil];}
- (PSSpecifier*)button:(NSString*)name action:(SEL)action pid:(NSString*)pid {PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:NULL get:NULL detail:Nil cell:PSButtonCell edit:Nil];s.buttonAction=action;if(pid)[s setProperty:pid forKey:@"jid"];return s;}
- (PSSpecifier*)toggle:(NSString*)name kind:(NSString*)kind jid:(NSString*)jid {PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:@selector(setValue:specifier:) get:@selector(value:) detail:Nil cell:PSSwitchCell edit:Nil];[s setProperty:kind forKey:@"kind"];if(jid)[s setProperty:jid forKey:@"jid"];return s;}
- (NSArray*)planned {NSDictionary *s=Status();if([s[@"preset"] isEqual:@"custom"])return s[@"custom"]?:@[];for(NSDictionary *p in Presets())if([p[@"id"] isEqual:s[@"preset"]])return p[@"jobs"];return @[];}
- (id)value:(PSSpecifier*)s {NSString *k=[s propertyForKey:@"kind"];NSDictionary *st=Status();if([k isEqual:@"master"])return st[@"enabled"]?:@NO;if([k isEqual:@"cc"])return @([st[@"ccPresets"] containsObject:[s propertyForKey:@"jid"]]);return @([[self planned] containsObject:[s propertyForKey:@"jid"]]);}
- (id)ramValue:(PSSpecifier*)s {NSDictionary *st=Status();return RAMText(st[@"ramSavedBytes"],st[@"ramSavedBytes"]!=nil);}
- (void)setValue:(id)v specifier:(PSSpecifier*)s {NSString *k=[s propertyForKey:@"kind"];if([k isEqual:@"master"])[self send:[v boolValue]?@"on":@"off"];else [self send:[([k isEqual:@"cc"]?@"cc.":@"job.") stringByAppendingString:[s propertyForKey:@"jid"]]];}
- (void)choosePreset:(PSSpecifier*)s {[self send:[@"preset." stringByAppendingString:[s propertyForKey:@"jid"]]];}
- (void)message:(NSString*)text {UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Пресеты" message:text preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"ОК" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (void)libraryReply {NSDictionary *s=Status();if(self.pendingRequest && [s[@"libraryRequest"] isEqual:self.pendingRequest]){self.pendingRequest=nil;NSString *error=s[@"libraryError"];[self message:error.length?error:@"Изменения сохранены."];}}
- (void)request:(NSDictionary*)r {NSMutableDictionary *d=[r mutableCopy];self.pendingRequest=NSUUID.UUID.UUIDString;d[@"request"]=self.pendingRequest;if(![d writeToFile:RPRequest atomically:YES]){self.pendingRequest=nil;[self message:@"Не удалось записать запрос."];return;}[self send:@"library"];}
- (void)savePreset:(PSSpecifier*)s {UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Сохранить текущий набор" message:@"Сохраняется выбранный состав служб, даже если твик сейчас выключен." preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"Название пресета";}];[a addAction:[UIAlertAction actionWithTitle:@"Отмена" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Сохранить" style:UIAlertActionStyleDefault handler:^(UIAlertAction *act){[self request:@{@"op":@"save",@"name":a.textFields.firstObject.text?:@""}];}]];[self presentViewController:a animated:YES completion:nil];}
- (void)deletePreset:(PSSpecifier*)s {NSString *pid=[s propertyForKey:@"jid"];UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Удалить свой пресет?" message:@"Активный состав останется индивидуальным набором. Пресет исчезнет из списка пункта управления." preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"Отмена" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Удалить" style:UIAlertActionStyleDestructive handler:^(UIAlertAction *act){[self request:@{@"op":@"delete",@"id":pid}];}]];[self presentViewController:a animated:YES completion:nil];}
- (BOOL)tableView:(UITableView*)tableView canEditRowAtIndexPath:(NSIndexPath*)indexPath {return [[self pageKind] isEqual:@"presets"] && [[[self specifierAtIndexPath:indexPath] propertyForKey:@"jid"] hasPrefix:@"user"];}
- (UISwipeActionsConfiguration*)tableView:(UITableView*)tableView trailingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath*)indexPath {
 if(![self tableView:tableView canEditRowAtIndexPath:indexPath])return nil;
 NSString *pid=[[self specifierAtIndexPath:indexPath] propertyForKey:@"jid"];
 UIContextualAction *action=[UIContextualAction contextualActionWithStyle:UIContextualActionStyleDestructive title:@"Удалить" handler:^(UIContextualAction *act,UIView *view,void(^done)(BOOL)){[self request:@{@"op":@"delete",@"id":pid}];done(YES);}];
 UISwipeActionsConfiguration *config=[UISwipeActionsConfiguration configurationWithActions:@[action]];config.performsFirstActionWithFullSwipe=NO;return config;
}
- (void)exportRecords:(NSArray*)records {NSMutableArray *out=[NSMutableArray array];NSDictionary *cat=Catalog();for(NSDictionary *p in records){NSMutableArray *labels=[NSMutableArray array];for(NSString *jid in p[@"jobs"])for(NSDictionary *j in cat[@"jobs"])if([j[@"id"] isEqual:jid])[labels addObject:j[@"label"]];[out addObject:@{@"name":p[@"name"],@"jobs":labels}];}if(!out.count){[self message:@"Сначала сохраните свой пресет."];return;}NSData *d=[NSJSONSerialization dataWithJSONObject:@{@"schema":@1,@"presets":out} options:NSJSONWritingPrettyPrinted error:nil];NSString *dir=@"/var/mobile/Documents/DaemonPresets";[[NSFileManager defaultManager] createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];NSURL *url=[NSURL fileURLWithPath:[dir stringByAppendingPathComponent:[NSString stringWithFormat:@"daemon-presets-%@.json",NSUUID.UUID.UUIDString]]];if(![d writeToURL:url atomically:YES]){[self message:@"Не удалось создать файл экспорта."];return;}UIActivityViewController *vc=[[UIActivityViewController alloc] initWithActivityItems:@[url] applicationActivities:nil];if(vc.popoverPresentationController){vc.popoverPresentationController.sourceView=self.view;vc.popoverPresentationController.sourceRect=self.view.bounds;}[self presentViewController:vc animated:YES completion:nil];}
- (void)exportCurrent:(PSSpecifier*)s {NSString *name=@"Индивидуальный набор";for(NSDictionary *p in Presets())if([p[@"id"] isEqual:Status()[@"preset"]])name=p[@"name"];[self exportRecords:@[@{@"name":name,@"jobs":[self planned]}]];}
- (void)exportLibrary:(PSSpecifier*)s {[self exportRecords:Status()[@"userPresets"]?:@[]];}
- (void)copyCurrentJSON:(PSSpecifier*)s {NSMutableArray *labels=[NSMutableArray array];NSDictionary *cat=Catalog();for(NSString *jid in [self planned])for(NSDictionary *j in cat[@"jobs"])if([j[@"id"] isEqual:jid])[labels addObject:j[@"label"]];NSString *name=@"Индивидуальный набор";for(NSDictionary *p in Presets())if([p[@"id"] isEqual:Status()[@"preset"]])name=p[@"name"];NSData *d=[NSJSONSerialization dataWithJSONObject:@{@"schema":@1,@"presets":@[@{@"name":name,@"jobs":labels}]} options:NSJSONWritingPrettyPrinted error:nil];UIPasteboard.generalPasteboard.string=[[NSString alloc] initWithData:d encoding:NSUTF8StringEncoding];[self message:@"JSON текущего набора скопирован."];}
- (void)importClipboard:(PSSpecifier*)s {NSString *text=UIPasteboard.generalPasteboard.string;NSData *d=[text dataUsingEncoding:NSUTF8StringEncoding];id doc=d.length && d.length<=60000?[NSJSONSerialization JSONObjectWithData:d options:0 error:nil]:nil;if(![doc isKindOfClass:NSDictionary.class]){[self message:@"В буфере нужен JSON пресетов размером до 60 КБ."];return;}[self request:@{@"op":@"import",@"document":doc}];}
- (void)importFile:(PSSpecifier*)s {UIDocumentPickerViewController *picker=[[UIDocumentPickerViewController alloc] initForOpeningContentTypes:@[UTTypeJSON,UTTypeText] asCopy:YES];picker.delegate=self;picker.allowsMultipleSelection=NO;[self presentViewController:picker animated:YES completion:nil];}
- (void)documentPicker:(UIDocumentPickerViewController*)controller didPickDocumentsAtURLs:(NSArray<NSURL*>*)urls {NSURL *url=urls.firstObject;if(!url)return;BOOL scoped=[url startAccessingSecurityScopedResource];NSNumber *size=nil;[url getResourceValue:&size forKey:NSURLFileSizeKey error:nil];NSData *d=(size && size.unsignedIntegerValue<=60000)?[NSData dataWithContentsOfURL:url]:nil;if(scoped)[url stopAccessingSecurityScopedResource];id doc=d?[NSJSONSerialization JSONObjectWithData:d options:0 error:nil]:nil;if(![doc isKindOfClass:NSDictionary.class]){[self message:@"Нужен файл JSON размером до 60 КБ, экспортированный этим твиком."];return;}[self request:@{@"op":@"import",@"document":doc}];}
- (NSArray*)specifiers {if(_specifiers)return _specifiers;NSDictionary *st=Status();NSMutableArray *a=[NSMutableArray array];NSString *page=[self pageKind];NSString *health=!st.count?@"Нет ответа управляющей службы":[st[@"verified"] boolValue]?@"Состояния launchd подтверждены":@"Состояние применения ещё не подтверждено";
 if([page isEqual:@"menu"]){NSString *preset=@"Не выбран";for(NSDictionary *p in Presets())if([p[@"id"] isEqual:st[@"preset"]])preset=p[@"name"];[a addObject:[self group:@"Настройки" footer:[NSString stringWithFormat:@"Набор: %@. %@. ВЫКЛ восстанавливает исходные состояния служб. Выбор набора при выключенном твике сохраняется до включения.",preset,health]]];[a addObject:[self toggle:@"Включить твик" kind:@"master" jid:nil]];[a addObject:[self group:@"Оперативная память" footer:[NSString stringWithFormat:@"Оценка по фактическому расходу процессов перед отключением. Общие процессы считаются один раз. Это не прирост свободной RAM всей iOS. МБ = 1 000 000 байт.%@",[st[@"ramMissingJobs"] unsignedIntegerValue]?@" Для части отключённых служб нет замера; они не включены в сумму.":@""]]];[a addObject:[PSSpecifier preferenceSpecifierNamed:@"Экономия RAM" target:self set:NULL get:@selector(ramValue:) detail:Nil cell:PSStaticTextCell edit:Nil]];if([st[@"errors"] count])[a addObject:[self group:@"Ошибка" footer:[st[@"errors"] componentsJoinedByString:@"\n"]]];[a addObject:[self group:@"Управление" footer:@"Короткое нажатие в пункте управления включает или выключает твик. Долгое открывает выбранные пресеты."]];[a addObject:[self link:@"Пресеты" detail:RPPresetsController.class]];[a addObject:[self link:@"Демоны" detail:RPDaemonsController.class]];[a addObject:[self link:@"Пресеты в пункте управления" detail:RPCCController.class]];}
 if([page isEqual:@"presets"]){[a addObject:[self group:@"Готовые наборы" footer:@"Выбор заменяет состав отключаемых служб. Фотоанализ приостанавливает новую индексацию и распознавание фото."]];for(NSDictionary *p in Catalog()[@"presets"])[a addObject:[self button:[NSString stringWithFormat:@"%@%@",[p[@"id"] isEqual:st[@"preset"]]?@"✓ ":@"",p[@"name"]] action:@selector(choosePreset:) pid:p[@"id"]]];[a addObject:[self group:@"Свои пресеты" footer:@"Сначала выберите службы или готовый набор, затем сохраните состав под своим названием. До 32 пресетов. Удаление — свайп влево по строке. Наборы с одинаковым названием сохраняются отдельно."]];[a addObject:[self button:@"Сохранить текущий набор…" action:@selector(savePreset:) pid:nil]];for(NSDictionary *p in st[@"userPresets"]){[a addObject:[self button:[NSString stringWithFormat:@"%@%@",[p[@"id"] isEqual:st[@"preset"]]?@"✓ ":@"",p[@"name"]] action:@selector(choosePreset:) pid:p[@"id"]]];}[a addObject:[self group:@"Перенос пресетов" footer:@"Экспорт сохраняет JSON в Documents/DaemonPresets и открывает «Поделиться». Доступен также перенос через буфер обмена. Импорт добавляет свои пресеты и не включает твик. Файлы с защищёнными или неизвестными службами отклоняются целиком."]];[a addObject:[self button:@"Экспортировать текущий набор…" action:@selector(exportCurrent:) pid:nil]];[a addObject:[self button:@"Экспортировать свои пресеты…" action:@selector(exportLibrary:) pid:nil]];[a addObject:[self button:@"Импортировать из файла…" action:@selector(importFile:) pid:nil]];[a addObject:[self button:@"Скопировать JSON текущего набора" action:@selector(copyCurrentJSON:) pid:nil]];[a addObject:[self button:@"Импортировать JSON из буфера" action:@selector(importClipboard:) pid:nil]];}
 if([page isEqual:@"cc"]){[a addObject:[self group:@"Список долгого нажатия" footer:@"В пункте управления появляются только выбранные здесь наборы, включая свои. Если ничего не выбрано, список будет пуст."]];for(NSDictionary *p in Presets())[a addObject:[self toggle:p[@"name"] kind:@"cc" jid:p[@"id"]]];}
 if([page isEqual:@"jobs"]){[a addObject:[self group:@"Каталог этого устройства" footer:@"Отключаемые демоны доступны для управления с указанными ограничениями. Защищённые службы перечислены для справки. Непроверенные также заблокированы: отсутствие проверки не означает, что служба критическая."]];[a addObject:[self link:[NSString stringWithFormat:@"Отключаемые (%lu демонов)",(unsigned long)[Catalog()[@"jobs"] count]] detail:RPReviewedController.class]];[a addObject:[self link:@"Критические (неотключаемые)" detail:RPProtectedController.class]];}
 if([page isEqual:@"reviewed"]){[a addObject:[self group:@"Отключать в выбранном наборе" footer:@"RAM рядом с именем — текущий расход процесса; у отключённой службы — замер перед отключением. Спящий демон показывает 0 МБ. Значения обновляются при открытии страницы и переключениях. Переключатель означает «отключать в наборе». Изменение создаёт индивидуальный набор. Проверка управления не означает, что отключение подходит всем: учитывайте описание функции."]];for(NSDictionary *j in Catalog()[@"jobs"]){NSDictionary *live=st[@"jobs"][j[@"id"]];[a addObject:[self group:@"" footer:[NSString stringWithFormat:@"%@\n%@: %@; %@.",j[@"note"],j[@"label"],[live[@"disabled"] boolValue]?@"запуск запрещён":@"запуск разрешён",[live[@"loaded"] boolValue]?@"служба загружена":@"служба выгружена"]]];[a addObject:[self toggle:[NSString stringWithFormat:@"%@ · %@",j[@"name"],RAMText(live[@"ramBytes"],[live[@"ramKnown"] boolValue])] kind:@"job" jid:j[@"id"]]];}}
 _specifiers=a;return a;}
@end
@implementation RPPresetsController
- (NSString*)pageKind {return @"presets";}
@end
@implementation RPDaemonsController
- (NSString*)pageKind {return @"jobs";}
@end
@implementation RPCCController
- (NSString*)pageKind {return @"cc";}
@end
@implementation RPReviewedController
- (NSString*)pageKind {return @"reviewed";}
@end
@implementation RPProtectedController
- (instancetype)init {if((self=[super init])){__weak RPProtectedController *w=self;notify_register_dispatch("com.ratush.daemonpresets.changed",&_memoryToken,dispatch_get_main_queue(),^(int t){[w.tableView reloadData];});}return self;}
- (void)dealloc {notify_cancel(_memoryToken);}
- (void)viewWillAppear:(BOOL)animated {[super viewWillAppear:animated];Command(@"query");[self.tableView reloadData];}
- (void)viewDidLoad {[super viewDidLoad];self.tableView=[[UITableView alloc] initWithFrame:self.view.bounds style:UITableViewStyleInsetGrouped];self.tableView.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;self.tableView.delegate=self;self.tableView.dataSource=self;[self.view addSubview:self.tableView];self.title=@"Критические (неотключаемые)";self.tableView.rowHeight=56;self.tableView.estimatedRowHeight=56;UISearchBar *search=[[UISearchBar alloc] init];search.placeholder=@"Поиск по имени службы";search.delegate=self;[search sizeToFit];self.tableView.tableHeaderView=search;UIActivityIndicatorView *spinner=[[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium];[spinner startAnimating];self.tableView.backgroundView=spinner;
 dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{@autoreleasepool{NSMutableSet *reviewed=[NSMutableSet set];for(NSDictionary *j in Catalog()[@"jobs"])[reviewed addObject:j[@"label"]];NSDictionary *critical=@{@"com.apple.backboardd":@"Ввод и графическая оболочка",@"com.apple.SpringBoard":@"Домашний экран",@"com.apple.cfprefsd.xpc.daemon":@"Системные настройки",@"com.apple.mobile.lockdown":@"Подключение и доверие устройства",@"com.apple.securityd":@"Связка ключей и безопасность",@"com.apple.trustd":@"Проверка сертификатов",@"com.apple.runningboardd":@"Жизненный цикл приложений",@"com.apple.assertiond":@"Жизненный цикл приложений",@"com.apple.notifyd":@"Уведомления процессов",@"com.apple.configd":@"Конфигурация сети",@"com.apple.mDNSResponder":@"Разрешение сетевых имён",@"com.apple.CommCenter":@"Сотовая связь",@"com.apple.wifid":@"Wi-Fi",@"com.apple.powerd":@"Питание и сон",@"com.apple.watchdogd":@"Контроль работоспособности",@"com.apple.logd":@"Системный журнал",@"com.apple.installd":@"Установка приложений",@"com.apple.lsd":@"Регистрация приложений",@"com.apple.tccd.system":@"Разрешения приложений",@"com.apple.nehelper":@"Сетевые расширения",@"com.apple.nesessionmanager":@"VPN и сетевые сеансы",@"com.ratush.daemonpresetsd":@"Управление этим твиком"};NSMutableDictionary *unique=[NSMutableDictionary dictionary];NSFileManager *fm=NSFileManager.defaultManager;
 for(NSString *dir in @[@"/System/Library/LaunchDaemons",@"/System/Library/LaunchAgents",@"/var/jb/Library/LaunchDaemons",@"/var/jb/Library/LaunchAgents"])for(NSString *file in [fm contentsOfDirectoryAtPath:dir error:nil]){@autoreleasepool{if(![file.pathExtension isEqual:@"plist"])continue;NSString *path=[dir stringByAppendingPathComponent:file];NSDictionary *d=[NSDictionary dictionaryWithContentsOfFile:path];NSString *label=d[@"Label"];if(![label isKindOfClass:NSString.class] || [reviewed containsObject:label])continue;NSString *role=critical[label];BOOL protected=role!=nil || [label containsString:@"sshd"] || [label containsString:@"jailbreak"] || [label containsString:@"dopamine"];NSString *note=protected?[NSString stringWithFormat:@"Критическая / защищённая: %@. Отключение заблокировано.",role?:@"доступ и работа jailbreak"]:@"Не проверена для отключения. Переключатель заблокирован; это не утверждение о критичности.";unique[label]=@{@"label":label,@"path":path,@"note":note,@"critical":@(protected)};}}
 NSArray *rows=[unique.allValues sortedArrayUsingComparator:^NSComparisonResult(NSDictionary *x,NSDictionary *y){if([x[@"critical"] boolValue]!=[y[@"critical"] boolValue])return [x[@"critical"] boolValue]?NSOrderedAscending:NSOrderedDescending;return [x[@"label"] localizedCaseInsensitiveCompare:y[@"label"]];}];dispatch_async(dispatch_get_main_queue(),^{self.inventory=rows;self.filtered=rows;self.tableView.backgroundView=nil;self.title=[NSString stringWithFormat:@"Критические (%lu демонов)",(unsigned long)rows.count];[self.tableView reloadData];});}});}
- (void)searchBar:(UISearchBar*)searchBar textDidChange:(NSString*)text {if(!text.length)self.filtered=self.inventory;else {NSMutableArray *a=[NSMutableArray array];for(NSDictionary *j in self.inventory)if([j[@"label"] localizedCaseInsensitiveContainsString:text])[a addObject:j];self.filtered=a;}[self.tableView reloadData];}
- (NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section {return self.filtered.count;}
- (UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)path {
 RPCatalogCell *cell=[tableView dequeueReusableCellWithIdentifier:@"locked"];if(!cell)cell=[[RPCatalogCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"locked"];
 NSDictionary *j=self.filtered[path.row],*mem=Status()[@"ramByLabel"][j[@"label"]];cell.nameLabel.text=[NSString stringWithFormat:@"%@\nRAM: %@",j[@"label"],RAMText(mem[@"bytes"],[mem[@"known"] boolValue])];cell.infoButton.accessibilityIdentifier=j[@"label"];cell.infoButton.accessibilityLabel=[@"Информация о " stringByAppendingString:j[@"label"]];[cell.infoButton removeTarget:nil action:NULL forControlEvents:UIControlEventTouchUpInside];[cell.infoButton addTarget:self action:@selector(infoPressed:) forControlEvents:UIControlEventTouchUpInside];return cell;
}
- (void)infoPressed:(UIButton*)button {NSDictionary *j=nil;for(NSDictionary *row in self.inventory)if([row[@"label"] isEqual:button.accessibilityIdentifier]){j=row;break;}if(!j)return;UIAlertController *a=[UIAlertController alertControllerWithTitle:j[@"label"] message:[NSString stringWithFormat:@"%@\n\n%@",j[@"note"],j[@"path"]] preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"ОК" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (NSString*)tableView:(UITableView*)tableView titleForHeaderInSection:(NSInteger)section {return @"Отключать запрещено • переключатели заблокированы";}
@end
